### ISSUE TITLE
Issue with APN for tele2.se

### ISSUE THREAD

**Issue by newlund** [SAOSP-L/Bug-tracker#11]
Mobile data for tele2 in Sweden is not working in latest build (Mako (Theme Engine build) 5/08)

<apn carrier="Tele2" apn="internet.tele2.se"

I had to delete the default APN's and create a new in order to get it to work. Perhaps the APN can be updated from stock rom?

**Comment by newlund** [comment]
Strange...
I compared the APNs with stock ROM and it was identical. Perhaps something else caused this. Issue can probably be closed...

**Comment by dexmc** [comment]
Closed
