### ISSUE TITLE
Advanced reboot

### ISSUE THREAD

**Issue by delaanthonio** [SAOSP-L/Bug-tracker#12]
Do you use Xposed framework? If yes, do not even bother reporting.
Uninstall Xposed(&reboot), check if the bug you're trying to report still
exists and then proceed. Otherwise,your report will be declared invalid.

Your device: Flounder

Which ROM version are you using? (provide download link)
https://mega.co.nz/#!QRZRzIRJ!0NK2G1KDQUYnKR5ooTKPo7j7J8-sL0rcLVZKNdyd3Fc

What kernel are you using - included in the ROM or from another source?
(provide xda/download link) 

What steps will reproduce the problem?
1. Open power menu
2. Select reboot
3. Select recovery

What is the expected result? What do you see instead?
I expect the device to boot into recovery but instead it does a normal reboot.

Is the result seen after a clean flash too?
Yes

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.

**Comment by Beta1440** [comment]
This problem seems to have been fixed by flashing the latest boot-loader in the factory images.

**Comment by delaanthonio** [comment]
The problem has been solved by disabling advanced reboot and enabling it again.
