### ISSUE TITLE
Bluetooth Issue

### ISSUE THREAD

**Issue by delaanthonio** [SAOSP-L/Bug-tracker#13]
Your device: Flounder

Which ROM version are you using? (provide download link):

Latest SAOSP source for flounder

What kernel are you using - included in the ROM or from another source?
(provide xda/download link)

What steps will reproduce the problem?
1. Enable bluetooth in settings

What is the expected result? What do you see instead?
 Bluetooth should turn on. Bluetooth turns off.

Is the result seen after a clean flash too?
Yes

Logcat:
http://pastebin.com/ccsD0Spj

**Comment by snak3ater** [comment]
What blobs are you using in flounder build?

**Comment by delaanthonio** [comment]
This bug has been fixed by this commit: https://github.com/DirtyUnicorns/android_device_htc_flounder/commit/683eb291db9bad5caf50fbd88113d8b19010b4b5
