### ISSUE TITLE
Sound and Notifications Settings FC

### ISSUE THREAD

**Issue by delaanthonio** [SAOSP-L/Bug-tracker#14]
Your device: Flounder

Which ROM version are you using? (provide download link)
LMY48B 5.1.1r3

What kernel are you using - included in the ROM or from another source?
(provide xda/download link)
Stock

What steps will reproduce the problem?
1. Open sound settings
2. Click on sound and notifications

What is the expected result? What do you see instead?
The sound and notifications menu should show up. Instead the settings app force closes.

Is the result seen after a clean flash too?
Yes

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.

http://pastebin.com/wrZJdX01

**Comment by snak3ater** [comment]
Fixed
