### ISSUE TITLE
Google Play Service FC when GPS enable

### ISSUE THREAD

**Issue by KenFa** [SAOSP-L/Bug-tracker#15]
Hello !

Config : lastest mako build (clean install) + lastest banks gapps + lastest Google Play Services apk

Google Play Service has FC when GPS (high accuracy mode) is enable. i don't have FC when GPS is set to device only. 

I found this on xda Slim Gapps thread : 
"Just a note. The new Slim Roms with 48B I am not having the fc issue. Could there be some permission issues in 48B that Slim has delt with in the rom that other devs have not yet. Just a thought. I was having the fc issue in other roms but not on slim."

Logcat : http://www.mediafire.com/view/doryeqo26do9pf1/2015-05-25-21-54-42.txt

**Comment by snak3ater** [comment]
Fixed
